baseurl: "/"
languageCode: en-US
languageLang: en
title: Ante Mihalj personal website
pluralizelisttitles: false
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  sitename: AnteMihalj
  copyright: Ante Mihalj
  powerBy: github.com
  github: amihalj
  googleVerification: KzRGJoaKbFQdMon_w38jhXmZz4dBGs76oKRVecKrwhg
  googleTrackingId: UA-108440761-2
  social:
    twitter: https://twitter.com/ante_mihalj
    facebook: https://www.facebook.com/ante.mihalj.94
    linkedin: https://www.linkedin.com/in/ante-mihalj-a3558050/
    github: https://github.com/amihalj
  contact:
    email: ante.mihalj@gmail.com
    address: null
    mobile: null
  author:
    name: Ante Mihalj
    about: My name is Ante
    contact:
      email: ante.mihalj@gmail.com
    image: 
      small: /img/avatar.jpg
      medium: /img/avatar.jpg
      big: /img/avatar.jpg
    social:
      twitter: null
      facebook: null
      instagram: null
      google: null

menu:
    top:
    - {Name: Home, Identifier: home, Url: "/", Weight: 10}
    #- {Name: Technologies, Identifier: technologies, Url: "/technologies/", Weight: 10}
    #- {Name: Posts, Identifier: posts, Url: "/posts/", Weight: 20}